package com.taskflow.userservice.model;

import jakarta.persistence.*;
import lombok.*;

import java.util.Set;

@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /*
     * JPA entity representing an application user.
     * Fields:
     * - id: primary key generated by the DB
     * - email: unique identifier used as username / token subject
     * - password: hashed password (store only the hash)
     * - roles: authorities granted to the user (ManyToMany relationship)
     *
     * Lombok annotations generate constructors, getters, setters and a builder
     * so we can write concise code like User.builder().email(...).build().
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String email;

    @Column(nullable = false)
    private String password;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(
            name = "users_roles",
            joinColumns = @JoinColumn(name = "user_id"),
            inverseJoinColumns = @JoinColumn(name = "role_id")
    )
    private Set<Role> roles;
}
